resource_group_name = "goldbeck-smart-building-dev-rg"
location            = "swedencentral"
cluster_name        = "goldbeck-dev-aks"
dns_prefix          = "goldbeckdev"
environment         = "Development"