apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akhtarmoin07/goldbeck-smart-building.git'
    targetRevision: main
    path: gitops/clusters/dev  # <--- WATCHES ONLY DEV
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true